# Generated by Django 5.0.4 on 2024-12-02 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_genre'),
        ('transaction', '0004_alter_borrow_borrow_user_alter_transactions_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='book.book'),
        ),
    ]
