# Generated by Django 5.0.4 on 2024-07-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrower',
            field=models.ManyToManyField(blank=True, to='account.useraccount'),
        ),
    ]
