# Generated by Django 5.0.4 on 2024-12-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ppdf',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
