# Generated by Django 5.0.4 on 2024-12-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book/uploads/images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ppdf',
            field=models.FileField(blank=True, null=True, upload_to='book/uploads/files/'),
        ),
    ]
