# Generated by Django 5.0.4 on 2024-12-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
